### ISSUE TITLE
Please provide a screenshot of your base

### ISSUE THREAD

**Issue by nitingiganetics** [GabrielAgrela/ROKBOT#9]
Hello,

I was thinking of starting on something like this for learning and while looking found out what you have created. Thanks for sharing the work. I am planning to get this working and then try and add more stuff to it. 

While going through the script, it seems it need a specific city layout. Could please share a screenshot of what you had when you tested this? Saves a lot time figuring out manually one by one. Wanted to send this only to you but could not locate an email to contact you so created this issue hoping that you would take a look and reply back.

I did start earlier on finding gems on the map and then collect it. Was planning to add human behavior to avoid bot detection as well. Here is what I managed to put so far -

from python_imagesearch.imagesearch import imagesearch
from python_imagesearch.imagesearch import imagesearcharea
from python_imagesearch.imagesearch import imagesearch_count

from screen_search import *
import pyautogui
import random

def findGems():
    # note that the search only works on your primary screen.
    search = Search("gem3.png")
    pos = search.imagesearch()

    if pos[0] != -1:
        print("position : ", pos[0], pos[1])
        # Add random pixels for click on different location - Human behavior
        pyautogui.moveTo( pos[0] + random.randint( 1, 21 ), pos[1] + random.randint( 1, 21 ) )
        pyautogui.click()
    else:
        print("image not found")

def findGatherButtom():
    pos = imagesearcharea("gather.png", 0, 0, 1920, 1080)
    if pos[0] != -1:
        print("position : ", pos[0], pos[1])
        pyautogui.moveTo( pos[0] + random.randint( 1, 21 ), pos[1] + random.randint( 1, 21 ) )
    else:
        print("image not found")

def toggleOutOfCityAndZoomOut():
    pyautogui.moveTo( 1340 + random.randint( 1, 21 ), 680 + random.randint( 1, 21 ) )
    pyautogui.click()
    pyautogui.press( 'space' )
    pyautogui.write(['down', 'down', 'down', 'down', 'down', 'down', 'down', 'down', 'down'], interval=random.uniform( 0.5, 2.5 ) )

def scrollVertically():
    print( "not implemented" );
    #Positive scrolling will scroll up, negative scrolling will scroll down:
    # pyautogui.scroll(amount_to_scroll, x=moveToX, y=moveToY)

def scrollHorizontally():
    print( "not implemented" );
    #Positive scrolling will scroll up, negative scrolling will scroll down:
    # pyautogui.scroll(amount_to_scroll, x=moveToX, y=moveToY)
    
    # pyautogui.dragTo(100, 200, button='left')     # drag mouse to X of 100, Y of 200 while holding down left mouse button
    # pyautogui.dragTo(300, 400, 2, button='left')  # drag mouse to X of 300, Y of 400 over 2 seconds while holding down left mouse button
    
    # pyautogui.move(-30, None)   # move the mouse left 30 pixels.

# Help to find out where we are on the game map
def getCityCoordinates():
    print( "not implemented" );

screenWidth, screenHeight = pyautogui.size()
print( "screenWidth : ", screenWidth )
print( "screenHeight : ", screenHeight )

findGems()

Thanks,
Nitin

**Comment by GabrielAgrela** [comment]
Hey Nitin,

Sorry for the late response, how you know, I'm not actively working on this for now and college stuff delayed this.
I added the screenshot at the end of the README.

Cheers.

**Comment by nitingiganetics** [comment]
Hey,
Thanks for getting back and providing the requested data. I went ahead on my own that I started earlier but still it is not yet at the level where I can validate it on the real game. 

I am still working on bunch of images to set the actions and hope I could finish at least a few. The real challenge I am finding is to zoom in and out in a way efficient enough and human behavior so that the game does not catch its a bot playing.
Also the image recognition somehow does not work well on negative scenarios. I tried a few approaches but none seem perfect. Also the confidence level they say, doesn't seem to help much to decide where something is there or not.
Well, I will keep you updating on the progress if you would like that.

Thanks again,Nitin
    On Friday, March 19, 2021, 5:01:48 PM GMT+5:30, Gabriel Agrela ***@***.***> wrote:  
 
 


Closed #9.

**Comment by GabrielAgrela** [comment]
Hey,

As far as the game thinking you are a bot or not, I found they don't really seem to care. My Captcha functionality has a success rate of like 1% per try (skips around 90% of the captchas and most of the ones it tries to guess fails). 
That means sometimes it takes an hour of almost trial an error to get past the captcha and I never got banned.

What are you referring to in the "image recognition" part? The captcha?

Not sure if you are having the same problem I had with zoom/swipes but I found some adb commands to be unreliable. IIRC, I tried using swipe to zoom out manually (contrary to tapping the city/map button to zoom to a default value) and there seems to be an acceleration or something that doesn't make the pixel distance travel linear (for example, even though my bot could guess correctly where each piece should go, I wasn't able to make the puzzle mini game functionality because of that inconsistence, because dragging the piece with the swipe command didn't always work as expected, specially given that I tried to make the bot to be the fastest possible. Anyways, I probably did something wrong).

But yeah, this is/was a personal project for educational purposes so if you wanna log you journey here I'll be happy to check it.
